import './babel'
import './styles/styles.css'
import './script'
import './assets/cat.png'
import './assets/batman.png'
import './assets/hollywood.png'
import './assets/strippers.png'
import './assets/genre-1.png'
import './assets/genre-2.png'
import './assets/genre-3.png'
import './assets/genre-4.png'
import './assets/AMEDIA.svg'
// import './styles/less.less'
// import './styles/scss.scss'

