import './styles/style.css'
import './babel.js'

import Cat from './assets/cat.png'
import Bat from './assets/batman.png'
import hollyWood from './assets/hollywood.png'
import strippers from './assets/strippers.png'
import genreOne from './assets/genre-1.png'
import genreTwo from './assets/genre-2.png'
import genreThree from './assets/genre-3.png'
import genreFour from './assets/genre-4.png'
