import './babel'
import './styles/styles.css'
import './script'
import './assets/images/logo.svg'
import './assets/images/profile-photo.png'
import './assets/images/icons/bell-icon.svg'
import './assets/images/icons/arrow-down.svg'
import './assets/images/cards/1.jpg'
import './assets/images/cards/2.jpg'
import './assets/images/cards/3.jpg'
import './assets/images/cards/4.jpg'
import './assets/images/cards/5.jpg'
import './assets/images/cards/6.jpg'
// import './assets/images/cards/7.jpg'
// import './assets/images/cards/8.jpg'
// import './assets/images/cards/9.jpg'
import './assets/images/icons/play-icon.svg'
import './assets/images/icons/photo-icon.svg'
import './assets/images/icons/audio-icon.svg'
import './assets/images/icons/point.svg'
// import './styles/less.less'
// import './styles/scss.scss'

